name: otodna
description: OtoDNA - Kuantum Araç Ağı ve Dijital Referans Protokolü
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_messaging: ^16.1.3
  mobile_scanner: ^7.2.0
  flutter_secure_storage: ^9.2.4
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7
  google_mlkit_text_recognition: ^0.13.1
  image_picker: ^1.2.1
  flutter_riverpod: ^3.2.1
  qr_flutter: ^4.1.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.3.10
  firebase_storage: ^13.2.0
  shared_preferences: ^2.5.4
  http: ^1.6.0
  intl: ^0.20.2

  # 🚀 SİBER GÖZ VE TORPİDO İÇİN EKLENEN KUANTUM MODÜLLERİ
  camera: ^0.11.0
  path: ^1.9.0

  # 🚀 SİBER EKLENTİLER (Mühürlü Raporları Üretmek ve Açmak İçin)
  open_file: ^3.3.2
  pdf: ^3.11.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 📂 KUANTUM MEDYA DEPOSU
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  # 🌑 TESLA MİMARİSİ: TAM OLED SİYAH (Eski lacivert imha edildi)
  adaptive_icon_background: "#000000"
  # Ön planda OtoDNA'nın siber mühürlü şeffaf logosu
  adaptive_icon_foreground: "assets/images/icon.png"